-- Persistent log of every adversarial Red→Blue cycle.
-- Each row stores the full event stream as JSONB so the UI can replay any run.

create table adversarial_runs (
  id                uuid primary key,          -- matches the run_id generated by the API
  org_id            uuid not null references organizations(id) on delete cascade,
  triggered_by      text not null default 'schedule',
  status            text not null default 'running'
                    check (status in ('running', 'completed', 'failed')),
  findings_created  int  not null default 0,
  responses_created int  not null default 0,
  events            jsonb not null default '[]',   -- full ordered event log for replay
  started_at        timestamptz not null default now(),
  completed_at      timestamptz
);

create index adversarial_runs_org_idx on adversarial_runs (org_id, started_at desc);

alter table adversarial_runs enable row level security;
create policy "org_isolation" on adversarial_runs
  using (org_id = current_org_id());
